// Code generated by gsx; DO NOT EDIT.

package uswds

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxio "io"
)

//line alert.gsx:5:1
// Alert is the USWDS alert (usa-alert), no-icon anatomy: a status-tinted
// panel with a thick status-colored left bar; the copy stays regular
// foreground ink (USWDS alerts never color their text — the tint and bar
// carry the status, keeping AA contrast on every variant). variant: "info"
// (default) | "success" | "warning" | "error". No icons are shipped —
// keeping the registry dependency-free — so the CSS renders the
// usa-alert--no-icon layout.

//line alert.gsx:12:1
func Alert(variant string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert.gsx:13:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"alert\"")
		}
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"alert\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-alert"), _gsxrt.Class(familyClass(variant)), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line alert.gsx:19:3
		_gsxgw.S("<div class=\"usa-alert__body\">")
//line alert.gsx:20:4
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div></div>")
		return _gsxgw.Err()
	})
}

//line alert.gsx:25:1
// AlertHeading is usa-alert__heading. It renders a div, not a fixed h4 —
// heading level belongs to the page's outline, not the component; wrap it
// in (or replace it with) the level your document needs.

//line alert.gsx:28:1
func AlertHeading(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert.gsx:29:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"alert-heading\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-alert__heading"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line alert.gsx:30:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line alert.gsx:34:1
func AlertText(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert.gsx:35:2
		_gsxgw.S("<p")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"alert-text\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-alert__text"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line alert.gsx:36:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}

//line alert.gsx:40:1
func familyClass(variant string) string {
	switch variant {
	case "success":
		return "usa-alert--success"
	case "warning":
		return "usa-alert--warning"
	case "error":
		return "usa-alert--error"
	default:
		return "usa-alert--info"
	}
}
