// Code generated by gsx; DO NOT EDIT.

package uswds

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	_gsxio "io"
)

//line button.gsx:5:1
// Button is the USWDS button (usa-button), typed for gsx. The variant
// vocabulary is USWDS's own modifier set — "" (primary), "outline", "base",
// "secondary", "big", "unstyled" — mapped to the corresponding
// usa-button--* class; unknown variants fall back to primary. A non-empty
// href on an enabled Button renders an <a> (same contract as gsxui's
// Button); disabled always renders a real disabled <button>. type="button"
// is an overridable default — pass type="submit" at the call site.
//
// Styling lives in css/uswds-components.css, keyed entirely off the
// usa-button classes; no Tailwind utilities are baked in, so callers can
// still adjust per-site with their own utility classes (the component CSS
// sits in @layer components, below Tailwind's utilities layer).
//
// Caution for shadcn/gsxui muscle memory: USWDS "secondary" is the RED
// secondary palette, not a quiet gray — for a subdued button use "base"
// (gray) or "outline".

//line button.gsx:21:1
func Button(variant string, href string, disabled bool, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line button.gsx:22:2
		if href != "" && !disabled {
//line button.gsx:23:3
			_gsxgw.S("<a")
			if !attrs.Has("data-slot") {
				_gsxgw.S(" data-slot=\"button\"")
			}
			if !attrs.Has("data-variant") {
				_gsxgw.S(" data-variant=\"")
				_gsxgw.AttrValue(string(_gsxstd.Default((variant), "default")))
				_gsxgw.S("\"")
			}
			if !attrs.Has("href") {
				_gsxgw.S(" href=\"")
				_gsxgw.URL(string(href))
				_gsxgw.S("\"")
			}
			_gsxgw.S(" class=\"")
			_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-button"), _gsxrt.Class(modifierClass(variant)), _gsxrt.Class(attrs.Class()))
			_gsxgw.S("\"")
			_gsxgw.StyleMerged("", attrs.Style())
			_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
			_gsxgw.S(">")
//line button.gsx:30:4
			_gsxgw.Node(ctx, children)
			_gsxgw.S("</a>")
		} else {
//line button.gsx:33:3
			_gsxgw.S("<button")
			if !attrs.Has("data-slot") {
				_gsxgw.S(" data-slot=\"button\"")
			}
			if !attrs.Has("data-variant") {
				_gsxgw.S(" data-variant=\"")
				_gsxgw.AttrValue(string(_gsxstd.Default((variant), "default")))
				_gsxgw.S("\"")
			}
			if !attrs.Has("type") {
				_gsxgw.S(" type=\"button\"")
			}
			_gsxgw.S(" class=\"")
			_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-button"), _gsxrt.Class(modifierClass(variant)), _gsxrt.Class(attrs.Class()))
			_gsxgw.S("\"")
			if !attrs.Has("disabled") {
				_gsxgw.BoolAttr("disabled", bool(disabled))
			}
			_gsxgw.StyleMerged("", attrs.Style())
			_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
			_gsxgw.S(">")
//line button.gsx:41:4
			_gsxgw.Node(ctx, children)
			_gsxgw.S("</button>")
		}
		return _gsxgw.Err()
	})
}

//line button.gsx:46:1
func modifierClass(variant string) string {
	switch variant {
	case "outline":
		return "usa-button--outline"
	case "base":
		return "usa-button--base"
	case "secondary":
		return "usa-button--secondary"
	case "big":
		return "usa-button--big"
	case "unstyled":
		return "usa-button--unstyled"
	default:
		return ""
	}
}
