// Code generated by gsx; DO NOT EDIT.

package uswds

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxio "io"
)

//line input.gsx:5:1
// Input is the USWDS text input (usa-input): 1px base-dark border, square
// corners, units(5) = 40px tall, with the USWDS focus convention (4px solid
// focus-color outline at offset 0). type="text" is an overridable default —
// pass type="email" etc. at the call site. Void, childless element: the
// explicit { attrs... } spread opts it into fallthrough. Styling lives in
// css/uswds-components.css under @layer components, so caller utility
// classes still win per property.

//line input.gsx:12:1
func Input(attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line input.gsx:13:2
		_gsxgw.S("<input")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"input\"")
		}
		if !attrs.Has("type") {
			_gsxgw.S(" type=\"text\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-input"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "xlink:href"}, []string{"background", "src"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
		return _gsxgw.Err()
	})
}
