// Code generated by gsx; DO NOT EDIT.

package uswds

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxio "io"
)

//line list.gsx:5:1
// ListBlockItem is the standard USWDS block layout. It uses left borders
// and background colors to indicate state.

//line list.gsx:7:1
func ListBlockItem(variant string, number string, title string, desc string, modifiers []string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line list.gsx:8:2
		_gsxgw.S("<li class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("relative p-4 rounded border flex items-start gap-4 hover:shadow-md"), _gsxrt.Class(blockBaseClass(variant, modifiers)), _gsxrt.Class(dimmedClass(variant, modifiers)), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line list.gsx:16:3
		_gsxgw.S("<div class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm bg-background border"), _gsxrt.Class(colorClass(variant, "border")), _gsxrt.Class(colorClass(variant, "text")))
		_gsxgw.S("\">")
//line list.gsx:17:4
		if variant == "success" {
//line list.gsx:18:5
			_gsxgw.S("<i data-lucide=\"check\" class=\"w-4 h-4\"></i>")
		} else {
//line list.gsx:20:5
			_gsxgw.Text(string(number))
		}
		_gsxgw.S("</div>")
//line list.gsx:23:3
		_gsxgw.S("<div>")
//line list.gsx:24:4
		_gsxgw.S("<div")
		_gsxv0 := "font-bold"
		var _gsxv1 string
		if variant == "disabled" {
			_gsxv1 = "line-through text-muted-foreground"
		} else {
			_gsxv1 = "text-foreground"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class(_gsxv0), _gsxrt.Class(_gsxv1))
		_gsxgw.S("\">")
//line list.gsx:24:125
		_gsxgw.Text(string(title))
		_gsxgw.S("</div>")
//line list.gsx:25:4
		_gsxgw.S("<div")
		_gsxv2 := "text-sm mt-0.5"
		var _gsxv3 string
		if variant == "disabled" {
			_gsxv3 = "line-through text-muted-foreground/70"
		} else {
			_gsxv3 = "text-muted-foreground"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class(_gsxv2), _gsxrt.Class(_gsxv3))
		_gsxgw.S("\">")
//line list.gsx:25:139
		_gsxgw.Text(string(desc))
		_gsxgw.S("</div></div></li>")
		return _gsxgw.Err()
	})
}

//line list.gsx:30:1
// ListMinimalRow is the tighter, table-like layout.

//line list.gsx:31:1
func ListMinimalRow(variant string, number string, title string, modifiers []string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line list.gsx:32:2
		_gsxgw.S("<li class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("flex items-center justify-between p-3 hover:bg-muted/50"), _gsxrt.Class(minimalBaseClass(variant, modifiers)), _gsxrt.Class(dimmedClass(variant, modifiers)), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line list.gsx:40:3
		_gsxgw.S("<div class=\"flex items-center gap-3\">")
//line list.gsx:41:4
		_gsxgw.S("<span class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("font-mono text-xs font-bold w-6 text-right"), _gsxrt.Class(colorClass(variant, "text")))
		_gsxgw.S("\">")
//line list.gsx:41:94
		_gsxgw.Text(string(number))
		_gsxgw.S(".</span>")
//line list.gsx:42:4
		_gsxgw.S("<span")
		_gsxv4 := "text-sm"
		var _gsxv5 string
		if variant == "disabled" {
			_gsxv5 = "line-through text-muted-foreground"
		} else {
			_gsxv5 = "font-medium text-foreground"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class(_gsxv4), _gsxrt.Class(_gsxv5))
		_gsxgw.S("\">")
//line list.gsx:42:136
		_gsxgw.Text(string(title))
		_gsxgw.S("</span></div>")
//line list.gsx:44:3
		if variant != "" && variant != "disabled" {
//line list.gsx:45:4
			_gsxgw.S("<i data-lucide=\"")
			_gsxgw.AttrValue(string(iconForVariant(variant)))
			_gsxgw.S("\" class=\"")
			_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("w-4 h-4"), _gsxrt.Class(colorClass(variant, "text")))
			_gsxgw.S("\"></i>")
		}
		_gsxgw.S("</li>")
		return _gsxgw.Err()
	})
}

//line list.gsx:50:1
// ListTaggedRow uses explicit tag components and icons.

//line list.gsx:51:1
func ListTaggedRow(variant string, number string, title string, desc string, modifiers []string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line list.gsx:52:2
		_gsxgw.S("<li class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("flex flex-col sm:flex-row sm:items-center justify-between p-4 gap-3 bg-background hover:bg-muted/50"), _gsxrt.Class(taggedBaseClass(modifiers)), _gsxrt.Class(dimmedClass(variant, modifiers)), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line list.gsx:60:3
		_gsxgw.S("<div>")
//line list.gsx:61:4
		_gsxgw.S("<div")
		_gsxv6 := "font-bold text-sm"
		var _gsxv7 string
		if variant == "disabled" {
			_gsxv7 = "text-muted-foreground"
		} else {
			_gsxv7 = "text-foreground"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class(_gsxv6), _gsxrt.Class(_gsxv7))
		_gsxgw.S("\">")
//line list.gsx:61:120
		_gsxgw.Text(string(number))
		_gsxgw.S(". ")
//line list.gsx:61:132
		_gsxgw.Text(string(title))
		_gsxgw.S("</div>")
//line list.gsx:62:4
		_gsxgw.S("<div class=\"text-xs text-muted-foreground mt-1\">")
//line list.gsx:62:52
		_gsxgw.Text(string(desc))
		_gsxgw.S("</div></div>")
//line list.gsx:64:3
		_gsxgw.S("<div class=\"flex-shrink-0 flex items-center\">")
//line list.gsx:65:4
		_gsxgw.Node(ctx, renderTag(variant))
//line list.gsx:66:4
		if hasModifier(modifiers, "archived") {
//line list.gsx:67:5
			_gsxgw.S("<span class=\"px-2 py-1 text-xs font-bold rounded bg-muted text-muted-foreground uppercase tracking-wider ml-1\">Archived</span>")
		}
		_gsxgw.S("</div></li>")
		return _gsxgw.Err()
	})
}

//line list.gsx:73:1
// ListProcessStep simulates a workflow step.

//line list.gsx:74:1
func ListProcessStep(variant string, number string, title string, desc string, isLast bool, modifiers []string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line list.gsx:75:2
		_gsxgw.S("<li")
		_gsxv8 := "relative pl-12 py-2 mb-4"
		var _gsxv9 string
		if hasModifier(modifiers, "dimmed") || hasModifier(modifiers, "archived") {
			_gsxv9 = "opacity-50"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class(_gsxv8), _gsxrt.Class(_gsxv9), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line list.gsx:82:3
		if !isLast {
//line list.gsx:83:4
			_gsxgw.S("<div class=\"")
			_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("absolute left-4 top-8 bottom-[-1.5rem] w-0.5 -ml-px z-0"), _gsxrt.Class(processLineClass(variant)))
			_gsxgw.S("\"></div>")
		}
//line list.gsx:85:3
		_gsxgw.S("<div class=\"absolute left-0 top-2\">")
//line list.gsx:86:4
		_gsxgw.S("<div class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("w-8 h-8 rounded-full border-2 flex items-center justify-center font-bold text-sm bg-background z-10 relative"), _gsxrt.Class(processCircleClass(variant)))
		_gsxgw.S("\">")
//line list.gsx:87:5
		if variant == "success" {
//line list.gsx:88:6
			_gsxgw.S("<i data-lucide=\"check\" class=\"w-4 h-4\"></i>")
		} else {
//line list.gsx:90:6
			_gsxgw.Text(string(number))
		}
		_gsxgw.S("</div></div>")
//line list.gsx:94:3
		_gsxgw.S("<div")
		var _gsxv10 string
		if variant == "disabled" {
			_gsxv10 = "text-muted-foreground"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class(_gsxv10))
		_gsxgw.S("\">")
//line list.gsx:95:4
		_gsxgw.S("<div")
		_gsxv11 := "font-bold text-sm"
		var _gsxv12 string
		if variant == "info" {
			_gsxv12 = "text-info"
		} else {
			_gsxv12 = "text-foreground"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class(_gsxv11), _gsxrt.Class(_gsxv12))
		_gsxgw.S("\">")
//line list.gsx:95:104
		_gsxgw.Text(string(title))
		_gsxgw.S("</div>")
//line list.gsx:96:4
		_gsxgw.S("<div class=\"text-xs text-muted-foreground mt-1\">")
//line list.gsx:96:52
		_gsxgw.Text(string(desc))
		_gsxgw.S("</div>")
//line list.gsx:97:4
		if variant == "error" {
//line list.gsx:98:5
			_gsxgw.S("<div class=\"mt-2 text-xs text-destructive bg-destructive-muted p-2 rounded inline-flex items-center gap-1 border border-destructive\">")
//line list.gsx:99:6
			_gsxgw.S("<i data-lucide=\"alert-circle\" class=\"w-3 h-3\"></i> Action required to proceed.</div>")
		}
		_gsxgw.S("</div></li>")
		return _gsxgw.Err()
	})
}

/*line list.gsx:104:2*/

// Helpers

func hasModifier(modifiers []string, m string) bool {
	for _, x := range modifiers {
		if x == m {
			return true
		}
	}
	return false
}

func dimmedClass(variant string, modifiers []string) string {
	if hasModifier(modifiers, "dimmed") || variant == "disabled" {
		return "opacity-60"
	}
	return ""
}

func blockBaseClass(variant string, modifiers []string) string {
	base := ""
	if hasModifier(modifiers, "archived") {
		base = "striped-archived border-muted-foreground "
	}
	switch variant {
	case "info":
		return base + "bg-info-muted border-l-4 border-info border-y-border border-r-border"
	case "success":
		return base + "bg-success-muted border-l-4 border-success border-y-border border-r-border"
	case "warning":
		return base + "bg-warning-muted border-l-4 border-warning border-y-border border-r-border"
	case "error":
		return base + "bg-destructive-muted border-l-4 border-destructive border-y-border border-r-border"
	case "disabled":
		return base + "bg-muted border-l-4 border-muted-foreground border-y-border border-r-border"
	default:
		if base != "" {
			return base + "border-border"
		}
		return "bg-background border-border"
	}
}

func minimalBaseClass(variant string, modifiers []string) string {
	base := ""
	if hasModifier(modifiers, "archived") {
		base = "striped-archived shadow-[inset_4px_0_0_0_var(--muted-foreground)] "
	}
	switch variant {
	case "info":
		return base + "bg-info-muted shadow-[inset_4px_0_0_0_var(--info)]"
	case "success":
		return base + "bg-success-muted shadow-[inset_4px_0_0_0_var(--success)]"
	case "warning":
		return base + "bg-warning-muted shadow-[inset_4px_0_0_0_var(--warning)]"
	case "error":
		return base + "bg-destructive-muted shadow-[inset_4px_0_0_0_var(--destructive)]"
	case "disabled":
		return base + "bg-muted shadow-[inset_4px_0_0_0_var(--muted-foreground)]"
	default:
		if base != "" {
			return base
		}
		return "bg-background"
	}
}

func taggedBaseClass(modifiers []string) string {
	if hasModifier(modifiers, "archived") {
		return "striped-archived"
	}
	return ""
}

func processLineClass(variant string) string {
	if variant == "success" {
		return "bg-success"
	}
	return "bg-border"
}

func processCircleClass(variant string) string {
	switch variant {
	case "success":
		return "bg-success border-success text-success-foreground"
	case "info":
		return "border-info text-info ring-4 ring-info-muted"
	case "warning":
		return "border-warning text-warning"
	case "error":
		return "border-destructive text-destructive"
	case "disabled":
		return "border-border text-muted-foreground bg-muted"
	default:
		return "border-border text-muted-foreground bg-muted"
	}
}

func colorClass(variant string, prop string) string {
	switch variant {
	case "info":
		return prop + "-info"
	case "success":
		return prop + "-success"
	case "warning":
		return prop + "-warning"
	case "error":
		return prop + "-destructive"
	case "disabled":
		return prop + "-muted-foreground"
	default:
		return prop + "-foreground"
	}
}

func iconForVariant(variant string) string {
	switch variant {
	case "info":
		return "chevron-right"
	case "success":
		return "check"
	case "warning":
		return "alert-circle"
	case "error":
		return "octagon-alert"
	default:
		return "circle"
	}
}

func renderTag(variant string) gsx.Node {
	switch variant {
	case "success":
		return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line list.gsx:238:10
			_gsxgw.S("<span class=\"px-2 py-1 text-xs font-bold rounded bg-success text-success-foreground uppercase tracking-wider\">Completed</span>")
			return _gsxgw.Err()
		}) /*line list.gsx:238:136*/
	case "warning":
		return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line list.gsx:240:10
			_gsxgw.S("<span class=\"px-2 py-1 text-xs font-bold rounded bg-warning text-warning-foreground uppercase tracking-wider flex items-center gap-1\">")
//line list.gsx:240:144
			_gsxgw.S("<i data-lucide=\"alert-triangle\" class=\"w-3 h-3\"></i> Draft</span>")
			return _gsxgw.Err()
		}) /*line list.gsx:240:209*/
	case "error":
		return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line list.gsx:242:10
			_gsxgw.S("<span class=\"px-2 py-1 text-xs font-bold rounded bg-destructive text-destructive-foreground uppercase tracking-wider flex items-center gap-1\">")
//line list.gsx:242:152
			_gsxgw.S("<i data-lucide=\"octagon-alert\" class=\"w-3 h-3\"></i> Alert</span>")
			return _gsxgw.Err()
		}) /*line list.gsx:242:216*/
	case "info":
		return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line list.gsx:244:10
			_gsxgw.S("<span class=\"px-2 py-1 text-xs font-bold rounded bg-info text-info-foreground uppercase tracking-wider\">Current</span>")
			return _gsxgw.Err()
		}) /*line list.gsx:244:128*/
	case "disabled":
		return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line list.gsx:246:10
			_gsxgw.S("<span class=\"px-2 py-1 text-xs font-bold rounded border border-muted-foreground text-muted-foreground uppercase tracking-wider\">Disabled</span>")
			return _gsxgw.Err()
		}) /*line list.gsx:246:153*/
	default:
		return nil
	}
}
