// Code generated by gsx; DO NOT EDIT.

package uswds

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	_gsxio "io"
)

//line modal.gsx:5:1
// Modal is USWDS's dialog (usa-modal), its documented anatomy —
// usa-modal__content > usa-modal__main, a heading, a footer, a corner
// close button — rendered onto a native <dialog> rather than USWDS's own
// usa-modal-wrapper/usa-modal-overlay pair and the JS behavior module
// that drives them. That JS exists to fake exactly what <dialog> already
// gives the platform for free: top-layer stacking above the rest of the
// page, an inert background, a real ::backdrop, and (via
// dialog.showModal()/.close(), or a plain <form method="dialog">) focus
// trapping and dismissal. This registry ships no JS at all — every other
// component here is server-rendered markup plus CSS, and Modal keeps
// that contract rather than becoming the one component that needs a
// script tag.
//
// A caller opens it with dialog.showModal() (an autoopen-style attribute
// plus a small event listener is the usual shape — see the README's
// Modal section) or wires open/close entirely through <form
// method="dialog"> buttons, which need no JS of the caller's either. The
// close button below already does the latter.
//
// closeLabel is the corner close button's aria-label ("Close" if empty).
// There's no icon glyph — USWDS's own close button is normally an SVG
// sprite reference, and this registry ships no icon assets (Alert's own
// "no icon" anatomy makes the same call) — just a plain "×" glyph.

//line modal.gsx:28:1
func Modal(closeLabel string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line modal.gsx:29:2
		_gsxgw.S("<dialog")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"modal\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-modal"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line modal.gsx:30:3
		_gsxgw.S("<div class=\"usa-modal__content\">")
//line modal.gsx:31:4
		_gsxgw.S("<div class=\"usa-modal__main\">")
//line modal.gsx:32:5
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
//line modal.gsx:34:4
		_gsxgw.S("<form method=\"dialog\">")
//line modal.gsx:35:5
		_gsxgw.S("<button type=\"submit\" class=\"usa-modal__close\" aria-label=\"")
		_gsxgw.AttrValue(string(_gsxstd.Default((closeLabel), "Close")))
		_gsxgw.S("\">×</button></form></div></dialog>")
		return _gsxgw.Err()
	})
}

//line modal.gsx:47:1
// ModalHeading is usa-modal__heading. Give it an id and point the Modal's
// own aria-labelledby at it — native <dialog> has no implicit label
// wiring the way usa-modal's own markup convention assumes, so the
// caller still owns that link (aria-describedby on the body text, the
// same way).

//line modal.gsx:52:1
func ModalHeading(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line modal.gsx:53:2
		_gsxgw.S("<h2")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"modal-heading\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-modal__heading"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line modal.gsx:54:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</h2>")
		return _gsxgw.Err()
	})
}

//line modal.gsx:58:1
// ModalFooter is usa-modal__footer — the button, or button group, that
// closes or acts on the dialog.

//line modal.gsx:60:1
func ModalFooter(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line modal.gsx:61:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"modal-footer\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-modal__footer"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line modal.gsx:62:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
