// Code generated by gsx; DO NOT EDIT.

package uswds

import (
	"strconv"

	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxio "io"
)

// RankedItem is one rung of a RankedList. Body is the row's content (it
// flexes to fill the row); Trailing is an optional right-aligned slot for
// annotations — a cost, a Tag, an action — kept separate so the body can
// wrap without pushing them off-row. Status draws the row's left status
// bar: "" (none — the gutter stays, transparent, so rows column-align) or
// "success". Muted grays the whole row — an item that is out of the
// running but keeps its place (rank is a fact even when the item didn't
// make the cut).
//
//line ranked-list.gsx:9:1
type RankedItem struct {
	Body     gsx.Node
	Trailing gsx.Node
	Status   string
	Muted    bool
}

// RankedList is a numbered standing. The <ol> carries the order
// semantically (screen readers announce position); the printed rank span
// is aria-hidden typography, styled in place of the list marker so the
// number sits inside the row's flex line. Not a stock USWDS component
// (registry extension): the anatomy borrows the alert's status left bar
// and the list's quiet row dividers, all on the usa-* tokens.
//
// waterline draws a labeled cutoff rule above items[waterline] — the
// budget line, the pass mark, the top-N fold. Pass -1 (or len(items)) for
// no line. It is an index, not a property of the items, because the line
// and the row status are independent facts: a greedy budget walk can fund
// a cheap item below the line, and that row keeps its success bar there.

//line ranked-list.gsx:36:1
func RankedList(items []RankedItem, waterline int, waterlineLabel string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line ranked-list.gsx:37:2
		_gsxgw.S("<ol")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"ranked-list\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-ranked-list"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line ranked-list.gsx:38:3
		for i, it := range items {
//line ranked-list.gsx:39:4
			if i == waterline {
//line ranked-list.gsx:40:5
				_gsxgw.S("<li data-slot=\"ranked-list-waterline\" class=\"usa-ranked-list__waterline\" role=\"presentation\">")
//line ranked-list.gsx:41:6
				_gsxgw.Text(string(waterlineLabel))
				_gsxgw.S("</li>")
			}
//line ranked-list.gsx:44:4
			_gsxgw.S("<li class=\"")
			_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-ranked-list__item"), _gsxrt.Class(rankedStatusClass(it)))
			_gsxgw.S("\">")
//line ranked-list.gsx:45:5
			_gsxgw.S("<span class=\"usa-ranked-list__rank\" aria-hidden=\"true\">")
//line ranked-list.gsx:45:60
			_gsxgw.Text(string(strconv.Itoa(i + 1)))
			_gsxgw.S(".</span>")
//line ranked-list.gsx:46:5
			_gsxgw.S("<span class=\"usa-ranked-list__body\">")
//line ranked-list.gsx:46:41
			_gsxgw.Node(ctx, it.Body)
			_gsxgw.S("</span>")
//line ranked-list.gsx:47:5
			if it.Trailing != nil {
//line ranked-list.gsx:48:6
				_gsxgw.Node(ctx, it.Trailing)
			}
			_gsxgw.S("</li>")
		}
		_gsxgw.S("</ol>")
		return _gsxgw.Err()
	})
}

//line ranked-list.gsx:55:1
func rankedStatusClass(it RankedItem) string {
	cls := ""
	if it.Status == "success" {
		cls = "usa-ranked-list__item--success"
	}
	if it.Muted {
		if cls != "" {
			cls += " "
		}
		cls += "usa-ranked-list__item--muted"
	}
	return cls
}
