// Code generated by gsx; DO NOT EDIT.

package uswds

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxio "io"
)

//line table.gsx:5:1
// Table is the USWDS table (usa-table). Unlike gsxui's table, there are no
// per-element subcomponents: USWDS styles thead/th/td by descendant
// selector, so callers write plain <thead>/<tbody>/<tr>/<th>/<td> (and an
// optional <caption>) as children and the anatomy just applies. variant:
// "" (bordered default) | "striped" | "borderless". compact tightens the
// cell padding (usa-table--compact, stackable with either variant).
// scrollable wraps the table in usa-table-container--scrollable — the USWDS
// pattern for wide tables: a focusable overflow region so keyboard users
// can pan it (hence tabindex="0" and role="region"; give it an aria-label
// via attrs when the table has no caption).

//line table.gsx:15:1
func Table(variant string, compact bool, scrollable bool, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line table.gsx:16:2
		if scrollable {
//line table.gsx:17:3
			_gsxgw.S("<div class=\"")
			_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-table-container--scrollable"), _gsxrt.Class(attrs.Class()))
			_gsxgw.S("\"")
			if !attrs.Has("tabindex") {
				_gsxgw.S(" tabindex=\"0\"")
			}
			if !attrs.Has("role") {
				_gsxgw.S(" role=\"region\"")
			}
			_gsxgw.StyleMerged("", attrs.Style())
			_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
			_gsxgw.S(">")
//line table.gsx:18:4
			_gsxgw.S("<table data-slot=\"table\" class=\"")
			_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-table"), _gsxrt.Class(tableVariantClass(variant)), _gsxrt.Class(tableCompactClass(compact)))
			_gsxgw.S("\">")
//line table.gsx:19:5
			_gsxgw.Node(ctx, children)
			_gsxgw.S("</table></div>")
		} else {
//line table.gsx:23:3
			_gsxgw.S("<table")
			if !attrs.Has("data-slot") {
				_gsxgw.S(" data-slot=\"table\"")
			}
			_gsxgw.S(" class=\"")
			_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-table"), _gsxrt.Class(tableVariantClass(variant)), _gsxrt.Class(tableCompactClass(compact)), _gsxrt.Class(attrs.Class()))
			_gsxgw.S("\"")
			_gsxgw.StyleMerged("", attrs.Style())
			_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
			_gsxgw.S(">")
//line table.gsx:24:4
			_gsxgw.Node(ctx, children)
			_gsxgw.S("</table>")
		}
		return _gsxgw.Err()
	})
}

//line table.gsx:29:1
func tableVariantClass(variant string) string {
	switch variant {
	case "striped":
		return "usa-table--striped"
	case "borderless":
		return "usa-table--borderless"
	default:
		return ""
	}
}

func tableCompactClass(compact bool) string {
	if compact {
		return "usa-table--compact"
	}
	return ""
}
