// Code generated by gsx; DO NOT EDIT.

package uswds

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxio "io"
)

//line tag.gsx:5:1
// Tag is the USWDS tag (usa-tag): the small uppercase label USWDS uses to
// mark an item's state — "Winner", "Funded", "New". It is a label, not a
// control: a <span>, no interaction states. big renders usa-tag--big (the
// 15px reading-size variant for body copy; the default is deliberately
// small and quiet). Status stays a caller concern — USWDS tags are one
// neutral gray; tint per-site with a utility class if you must, but the
// stock look is the accessible default.

//line tag.gsx:12:1
func Tag(big bool, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line tag.gsx:13:2
		_gsxgw.S("<span")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"tag\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("usa-tag"), _gsxrt.Class(tagBigClass(big)), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line tag.gsx:14:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</span>")
		return _gsxgw.Err()
	})
}

//line tag.gsx:18:1
func tagBigClass(big bool) string {
	if big {
		return "usa-tag--big"
	}
	return ""
}
